# Generated by Django 4.2.8 on 2025-11-13 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('asn_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã ASN')),
                ('deliverer_name', models.CharField(max_length=100, verbose_name='Người giao hàng')),
                ('deliverer_phone', models.CharField(max_length=20, verbose_name='SĐT người giao')),
                ('expected_date', models.DateField(verbose_name='Ngày dự kiến giao')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu giao hàng (ASN)',
                'verbose_name_plural': 'Phiếu giao hàng (ASN)',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã danh mục')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_code', models.CharField(max_length=20, unique=True, verbose_name='Mã phiếu nhập')),
                ('import_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ['-import_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('product_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('status', models.CharField(choices=[('active', 'Đang kinh doanh'), ('inactive', 'Ngừng kinh doanh')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã PO')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('closed', 'Đã đóng')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Đơn đặt hàng (PO)',
                'verbose_name_plural': 'Đơn đặt hàng (PO)',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('return_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã NCC')),
                ('company_name', models.CharField(max_length=200, verbose_name='Tên công ty')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Người liên hệ')),
                ('phone', models.CharField(max_length=15, verbose_name='SĐT')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Tạm dừng')], default='active', max_length=20, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('import', 'Nhập kho'), ('return', 'Hoàn hàng')], default='import', max_length=20, verbose_name='Loại lô')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Tồn kho')),
                ('unit', models.CharField(max_length=20, verbose_name='Đơn vị')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('status', models.CharField(choices=[('valid', 'Còn hạn'), ('nearly_expired', 'Cận hạn'), ('expired', 'Hết hạn')], default='valid', max_length=20, verbose_name='Trạng thái')),
                ('import_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='QuanLy.importreceipt', verbose_name='Phiếu nhập')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.productmaster', verbose_name='Sản phẩm')),
                ('return_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='QuanLy.returnreceipt', verbose_name='Phiếu hoàn')),
            ],
            options={
                'verbose_name': 'Hàng tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'ordering': ['expiry_date', 'product__product_code'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('detail_note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLy.productmaster')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QuanLy.returnreceipt')),
                ('stock_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã báo cáo')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Ngày tạo báo cáo')),
                ('total_imports', models.PositiveIntegerField(default=0, verbose_name='Số phiếu nhập')),
                ('total_exports', models.PositiveIntegerField(default=0, verbose_name='Số phiếu xuất')),
                ('total_returns', models.PositiveIntegerField(default=0, verbose_name='Số phiếu hoàn')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='Tổng tồn kho')),
                ('total_expired', models.PositiveIntegerField(default=0, verbose_name='Sản phẩm hết hạn')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Báo cáo thống kê',
                'verbose_name_plural': 'Báo cáo thống kê',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('unit', models.CharField(default='Thùng', max_length=20, verbose_name='Đơn vị')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QuanLy.purchaseorder', verbose_name='PO')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.productmaster', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm đặt hàng',
                'verbose_name_plural': 'Chi tiết đơn đặt hàng',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.supplier', verbose_name='Nhà cung ứng'),
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.supplier', verbose_name='Nhà cung ứng'),
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unit', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('import_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QuanLy.importreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLy.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ExportReceipt',
            fields=[
                ('export_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã phiếu xuất')),
                ('export_date', models.DateField(default=datetime.date.today, verbose_name='Ngày xuất')),
                ('destination', models.CharField(max_length=200, verbose_name='Nơi nhận')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
            },
        ),
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unit', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QuanLy.exportreceipt')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLy.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='ASNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng')),
                ('unit', models.CharField(max_length=20, verbose_name='Đơn vị')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='QuanLy.asn', verbose_name='ASN')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.productmaster', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm ASN',
                'verbose_name_plural': 'Chi tiết ASN',
            },
        ),
        migrations.AddField(
            model_name='asn',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.purchaseorder', verbose_name='Đơn đặt hàng (PO)'),
        ),
        migrations.AddField(
            model_name='asn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.supplier', verbose_name='Nhà cung ứng'),
        ),
    ]
