# Generated by Django 4.2.8 on 2025-10-26 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='Hộp', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Còn hàng'), ('low', 'Cận hạn'), ('out', 'Hết hàng')], default='available', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='QuanLy.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Tạm dừng')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_code', models.CharField(max_length=10, unique=True)),
                ('return_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('return_type', models.CharField(choices=[('customer', 'Khách hàng hoàn'), ('store', 'Cửa hàng hoàn')], max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('done', 'Đã xử lý'), ('processing', 'Đang xử lý')], default='done', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.product')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('total_imports', models.PositiveIntegerField(default=0)),
                ('total_exports', models.PositiveIntegerField(default=0)),
                ('total_returns', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_code', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_code', models.CharField(max_length=10, unique=True)),
                ('import_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('done', 'Hoàn thành'), ('processing', 'Đang xử lý')], default='processing', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ExportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_code', models.CharField(max_length=10, unique=True)),
                ('export_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('done', 'Hoàn thành'), ('delivering', 'Đang giao')], default='delivering', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.product')),
            ],
        ),
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn_code', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deliverer_name', models.CharField(max_length=100)),
                ('deliverer_phone', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('expected_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.supplier')),
            ],
        ),
    ]
