# Generated by Django 4.2.8 on 2025-11-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0003_category_image_productmaster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='asn',
            name='status',
            field=models.CharField(choices=[('not_delivered', 'Chưa giao'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao')], default='not_delivered', max_length=20, verbose_name='Trạng thái giao'),
        ),
        migrations.AddField(
            model_name='exportreceipt',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Người nhận'),
        ),
        migrations.AddField(
            model_name='exportreceipt',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT người nhận'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='asn_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.asnitem', verbose_name='Dòng ASN'),
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.asn', verbose_name='Phiếu ASN'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Thành tiền'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='export_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.exportitem', verbose_name='Dòng phiếu xuất'),
        ),
        migrations.AddField(
            model_name='returnreceipt',
            name='export_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.exportreceipt', verbose_name='Phiếu xuất tương ứng'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá tồn kho'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='QuanLy.category', verbose_name='Danh mục'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá NCC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang cung ứng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='QuanLy.productmaster', verbose_name='Sản phẩm')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='QuanLy.supplier', verbose_name='Nhà cung ứng')),
            ],
            options={
                'verbose_name': 'Sản phẩm nhà cung ứng',
                'verbose_name_plural': 'Sản phẩm nhà cung ứng',
                'unique_together': {('supplier', 'product')},
            },
        ),
        migrations.AddField(
            model_name='productmaster',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', through='QuanLy.SupplierProduct', to='QuanLy.supplier', verbose_name='Nhà cung ứng'),
        ),
    ]
