# Generated by Django 4.2.8 on 2025-11-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0004_asn_status_exportreceipt_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='suppliers',
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='QuanLy.productmaster'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='QuanLy.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
