# Generated by Django 4.2.8 on 2025-11-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0005_alter_supplierproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importreceipt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLy.category'),
        ),
    ]
