# Generated by Django 4.2.8 on 2025-11-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0006_importreceipt_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={'verbose_name': 'Sản phẩm nhà cung ứng', 'verbose_name_plural': 'Sản phẩm nhà cung ứng'},
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=set(),
        ),
    ]
