# Generated by Django 4.2.8 on 2025-11-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0007_alter_supplierproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={},
        ),
        migrations.AddField(
            model_name='returnitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='QuanLy.category', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Tên sản phẩm NCC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='product_code',
            field=models.CharField(default=2, max_length=30, verbose_name='Mã sản phẩm NCC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.supplierproduct', verbose_name='Sản phẩm NCC'),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLy.supplierproduct'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.supplierproduct', verbose_name='Sản phẩm NCC'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá NCC'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QuanLy.supplierproduct'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='stock_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_item', to='QuanLy.stockitem', verbose_name='Lô tồn kho hoàn'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLy.supplierproduct', verbose_name='Sản phẩm NCC'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá nhập'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang cung cấp'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='QuanLy.supplier', verbose_name='Nhà cung ứng'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá NCC'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together={('supplier', 'product_code')},
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductMaster',
        ),
    ]
