# Generated by Django 4.2.8 on 2025-11-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0008_alter_stockitem_options_returnitem_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importreceipt',
            name='import_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã phiếu nhập'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('closed', 'Hoàn tất')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
