# Generated by Django 4.2.8 on 2025-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0010_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='send_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
