# Generated by Django 4.2.8 on 2025-11-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLy', '0011_passwordresetotp_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Đơn giá NCC'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá'),
        ),
    ]
